#!/usr/bin/env python
from __future__ import print_function
import json, os, time

try:
    # For Python 3.0 and later
    from urllib.request import urlopen
except ImportError:
    # Fall back to Python 2's urllib2
    from urllib2 import urlopen

######################## CONSTANTS ########################
REPORT_CURRENCY_SHORT_NAME = 'USD' # ['USD', 'GBP', 'EUR']
REPORT_CURRENCY_SYMBOL = '$'
REQUEST_TIMEOUT_SECONDS = 2.5
CACHE_EXPIRE_SECONDS = 60*10
###########################################################

def get_json(url):
    return json.loads(urlopen(url, timeout=REQUEST_TIMEOUT_SECONDS).read().decode("utf-8"))

def get_btc_price_str():
    return REPORT_CURRENCY_SYMBOL + get_json('https://api.coindesk.com/v1/bpi/currentprice.json')['bpi'][REPORT_CURRENCY_SHORT_NAME]['rate'].split('.')[0]

splitter = '|'

try:
    cache_path = os.path.join(os.path.abspath(os.path.dirname(__file__)), '.btc_price_cache')

    if os.path.exists(cache_path):
        with open(cache_path, 'r') as f:
            comps = f.read().strip().split(splitter)
            ts = int(comps[0])

            if int(time.time()) - ts < CACHE_EXPIRE_SECONDS:
                print(comps[1])

                exit(0)
    
    price_str = get_btc_price_str()

    with open(cache_path, 'w') as f:
        f.write(str(int(time.time())) + splitter + price_str)

    print(price_str)
except Exception:
    print('<ERROR>')