#!/bin/bash

CACHE_PATH="$HOME/.btcpricesh"
MAX_CACHE_AGE_SECONDS=600 # 10 min
MIN_NETWORK_SPEED=25

delete_cache() {
    rm $CACHE_PATH
}

check_network_speed() {
    speed=$(/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | grep "lastTxRate:" | cut -d: -f2)

    if [ "$MIN_NETWORK_SPEED" -gt "$speed" ]; then
        exit 0
    fi
}

get_price_from_server() {
    check_network_speed

    # Uncomment if want other than USD
    # int_price=$(curl -m 0.5 -s "https://api.coindesk.com/v1/bpi/currentprice.json" | awk -F '\"code\":\"USD\"' '{print $2}' | awk -F 'rate_float\"\:' '{print $2}' | cut -d. -f1)
    int_price=$(curl -m 0.5 -s "https://api.coindesk.com/v1/bpi/currentprice.json" | awk -F 'rate_float\"\:' '{print $2}' | cut -d. -f1)

    if [ "$int_price" == "" ]; then
        exit 0
    fi

    int_price_k=$(echo "$int_price/1000" | bc)
    int_price_kt=$(expr $int_price_k \* 1000)
    int_price_k_remaining=$(expr $int_price - $int_price_kt)
    str_price_k_remaining_filled=$(printf "%03d" $int_price_k_remaining)

    price_str='$'$int_price_k","$str_price_k_remaining_filled

    touch $CACHE_PATH
    printf $price_str > $CACHE_PATH

    echo $price_str
}

flow() {
    if [ -f "$CACHE_PATH" ]; then
        # CACHE_PATH EXISTS
        cache_age_seconds=$(expr $(date +"%s") - $(date -r $CACHE_PATH +"%s"))

        if [ "$cache_age_seconds" -gt "$MAX_CACHE_AGE_SECONDS" ]; then
            delete_cache
            get_price_from_server
        else
            echo "$(cat $CACHE_PATH)"
        fi
    else
        get_price_from_server
    fi
}

flow